class Invalid < StandardError
end

class Client
  @socket: TCPSocket
  @buf: String

  def initialize: (TCPSocket socket) -> void

  def read_some: (?::Integer cnt) -> (true | false)

  def consume: () -> (Array[command])
end
