class Incomplete < StandardError
end

type command = String | Integer | nil | Array[command]

module CommandParser
  CRLF: String

  def self.read_complete_line: (StringIO io) -> String

  def self.decode: (StringIO io) -> command
end
