class Server
  @server: TCPServer
  @store: Hash[String, String]
  @clients: Hash[TCPSocket, Client]

  def initialize: (?Integer port) -> void

  def start: () -> void

  def clean: (TCPSocket) -> void

  def exec: (untyped command) -> String
end
